name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Menjalankan aksi ini setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Inject API URL Secret
        run: |
          # Mengganti kata kunci placeholder di script.js dengan isi dari GitHub Secret
          sed -i 's|ISI_API_URL_RAHASIA_DISINI|'${{ secrets.API_URL }}'|g' script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # Hasil injeksi akan dipublish ke branch gh-pages