name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Izin ini WAJIB ada agar robot bisa menyimpan perubahan URL ke branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Inject API URL Secret
        run: |
          # Menggunakan tanda kutip ganda (") agar secret terbaca dengan sempurna
          sed -i "s|ISI_API_URL_RAHASIA_DISINI|${{ secrets.API_URL }}|g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages