name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# TAMBAHKAN BLOK INI UNTUK MEMBERIKAN IZIN TULIS SECARA PAKSA
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # Menggunakan versi v4 agar warning Node.js hilang
        uses: actions/checkout@v4

      - name: Inject API URL Secret
        run: |
          sed -i 's|ISI_API_URL_RAHASIA_DISINI|'${{ secrets.API_URL }}'|g' script.js

      - name: Deploy to GitHub Pages
        # Menggunakan versi terbaru agar lebih stabil
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages